version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./app.db

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    # Optionnel : supprimer le volume pour éviter des conflits potentiels
    # volumes:
    #   - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000

networks:
  app-network:
    driver: bridge
